[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "https://www.foundtribesofisrael.com/*"
  to = "https://foundtribesofisrael.com/:splat"
  status = 301
